#===============================================================================
# Name : vars.yml
# purpose: 
#				This playbook explains how to use shell,command modules to execute commands
#           on nodes
# Diff between shell and command module:
# The shell module takes the command name followed by a list of space-delimited arguments.
# It is almost exactly like the command module but runs the command through a shell (/bin/sh) on the remote node.
#
# revisions:
#			11-24-2015,	UK,	shell Module
#===============================================================================
---
- hosts: centos7
  sudo: false
  gather_facts: false
  tasks:
   - name: check /tmp/shellexample.txt exists
     stat: path=/tmp/shellexample.txt
     register: p

   - name: delete /tmp/shellexample.txt file
     shell: rm -rf /tmp/shellexample.txt
     when: p.stat.exists == true

   - name: execute shell command and change dir
     shell: $HOME/shell.ksh
     args:
       chdir: /home/ukatru

#   - debug: var=p

   - name: execute command if file doesn't exists
     command: $HOME/shell.ksh
     args:
       creates: /tmp/shellexample.txt
