#===============================================================================
# Name : stat.yml
# purpose: 
#				This playbook explains how to use stat module to retrieve file 
#            or file system status          
# revisions:
#			11-24-2015,	UK,	Example stat task 
#===============================================================================
---
- hosts: centos7
  sudo: true
  gather_facts: false
  tasks:
    - stat: path=/etc/systemd/system/mysql.service
      register: service_status

# ====> setup percona repository
    - name: Install percona repository
      yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm state=present
      when: not service_status.stat.exists
