#===============================================================================
# Name : vars.yml
# purpose: 
#				This playbook explains how to define and use variables
#
# revisions:
#			11-24-2015,	UK,	Example variables
#===============================================================================
---
- hosts: centos7
  sudo: true
  gather_facts: true
  vars:
    pVar: uma
  tasks:
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]
    - debug: var=pVar
    - shell: /usr/bin/uptime
      register: result
    - debug: var=result.stdout
